language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
env:
install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 qt54tools qt54base
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && sudo apt-get install libssl-dev
      ;
    else
         brew tap PX4/homebrew-px4
      && brew update
      && brew install qt54
      && brew linkapps qt54
      && export PATH=/usr/local/opt/qt54/bin:$PATH
      ;
    fi

# install cmake
- CMAKE_VERSION="3.3.2"
- wget "http://www.cmake.org/files/v3.3/cmake-${CMAKE_VERSION}.tar.gz"
- tar xf "cmake-${CMAKE_VERSION}.tar.gz"
- cd "cmake-${CMAKE_VERSION}"
- ./configure --prefix=~
- make 
- make install
- export PATH="~/bin:${PATH}"
- cd ../
- rm -rf "cmake-${CMAKE_VERSION}"
- rm "cmake-${CMAKE_VERSION}.tar.gz"

script:
  - git submodule update --init --recursive 
  - cd build
  - sh ./rebuild.sh /dev/null /dev/null
after_success:
  - sh ./clean.sh
services:

notifications:
  recipients:
    - atopilski@fastogt.com
  email:
    on_success: change
    on_failure: change
