language: cpp
compiler:
  - gcc
env:

before_install:
- sudo apt-get install cmake
- sudo apt-get install qt5-qmake qtbase5-dev
- sudo apt-get install libssl-devel

script:
  - git submodule update --init --recursive 
  - cd build
  - sh ./rebuild.sh /dev/null /dev/null
after_success:
  - sh ./clean.sh
services:

notifications:
  recipients:
    - atopilski@fastogt.com
  email:
    on_success: change
    on_failure: change
